name: petvision_app
description: "PetVision AI Computer Vision Health Tracker"
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & DI
  flutter_riverpod: ^2.4.9    # (Will upgrade to 3.0 when released publicly stable)
  # Data Fetching / Networking
  http: ^1.2.0
  web_socket_channel: ^2.4.4
  # CV / Camera Hardware Access
  camera: ^0.10.5+9
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  # Routing
  go_router: ^13.2.0
  # UI & Charts
  fl_chart: ^0.66.0
  google_fonts: ^6.2.0
  intl: ^0.19.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
